server:
  port: 8081

spring:
    datasource:
      url: jdbc:mysql://localhost:3306/auth_db
      username: root
      password: Pranjal1308

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
